Add search to roster
ctoec/data-collection pull request #1438
Opened 2021-08-24 19:58 UTC by lukenewman

## Background
Added filtering functionality to the search bar on the roster redesign

## GitHub Issue
https://github.com/ctoec/data-collection/issues/1334

## Associated PRs
N/A

## Validation Plan
See associated issue/ticket. Filtering should match "first last" name formatting case-insensitively

## Automated Testing
- [ ] All unit tests are passing.
- [ ] If applicable, unit tests have been added to cover this changeset.

## Additional Context
N/A

2021-08-24 20:02 UTC, bamader approved these changes
LGTM!

2021-08-24 20:08 UTC, vonbearshark approved these changes

2021-08-24 20:37 UTC, JordanGuinn commented
We're unfortunately gonna need search to take place server-side here, as pagination will be coming up as part of this roster redesign relatively shortly 😕

2021-08-24 21:54 UTC, lukenewman commented
@JordanGuinn ahhh tfw you didn't even read the AC... 😬

2021-08-24 22:47 UTC, JordanGuinn commented
HEH, I've definitely never done THAT before, countless times... 😅😅

2021-09-01 15:47 UTC, vonbearshark requested changes

2021-09-01 15:47 UTC, vonbearshark commented on client/src/containers/Overview/Overview.tsx
> +import { apiGet } from '../../utils/api';
🤔  how was this working without this..?

2021-09-01 15:47 UTC, vonbearshark commented on src/migration/1630005495640-UpdateChildAddFullName.ts
> +}
Do we want this to be an actual property on the `Child`? Or would we prefer to just derive it on demand? I am not sure how we feel about derivative properties like this, but I have personally avoided them

2021-09-01 15:47 UTC, vonbearshark commented on src/routes/children.ts
> +    const children = await controller.getChildren(req.user, name);
Let's create a `Query` type that we can share between the route and controller and that can include `searchTerm`, `sorting`, `pagination`, etc. And then let's just pass the `req.query` into the `getChildren` fn and pull those props off the object

2021-09-01 15:47 UTC, vonbearshark commented on src/controllers/children/get.ts
> +  })
Might as well move this back to where it was? I guess it doesn't really matter, but ideally we filter on the `orgIds` first (even if it's just in the code flow and the generated SQL actions don't actually filter it first)

2021-09-01 15:47 UTC, vonbearshark commented on src/controllers/children/get.ts
> +    qb.andWhere('Child.fullName LIKE (:name)', {
Don't we want `ILike` so that the search is case-insensitive. I know we're converting `name` to lower, but won't `fullName` still be normally cased?

2021-09-01 15:47 UTC, vonbearshark commented on src/routes/children.ts
> +    const children = await controller.getChildren(req.user, name);
We could probably share the type with the client, too, even

2021-09-01 15:47 UTC, vonbearshark commented on client/src/containers/Roster/Roster.tsx
> +        }
We should be able to use `stringify` and `query-builder` for this. If you search for those in the codebase there should be examples

2021-09-01 15:47 UTC, vonbearshark commented on client/src/containers/Roster/Roster.tsx
> +        setChildRows(result.map(childToRow) ?? []);
FYI the `??` check shouldn't really do anything as is here. If result is undefined it's going try and map and throw an error (which is not caught with `??`), and if it is defined map will return an empty array at worst, which is truth-y. 
 You would want something like `result?.map(childToRow) ?? []`. But I actually don't think you need a check here, since `result` should either be defined or there should be a server error

2021-09-01 15:47 UTC, vonbearshark commented on client/src/containers/Roster/Roster.tsx
> +        setChildRows(result.map(childToRow) ?? []);
Actually, related, we should probably `try`/`catch` the request and handle a server error here

2021-09-01 15:50 UTC, vonbearshark commented
Functionally looking great! Just comments re: cleaning up the Roster interface really

2021-09-01 16:01 UTC, lukenewman commented on client/src/containers/Overview/Overview.tsx
> +import { apiGet } from '../../utils/api';
this was a result of `base` being merged into `EPIC-roster-redesign` and then me merging that into my branch

2021-09-01 16:03 UTC, lukenewman commented on src/migration/1630005495640-UpdateChildAddFullName.ts
> +}
this was taken directly from an acceptance criteria. are you opining that we can fetch firstName and lastName and then match temporary composite within query builder?

2021-09-01 16:03 UTC, lukenewman commented on src/controllers/children/get.ts
> +    qb.andWhere('Child.fullName LIKE (:name)', {
for the life of me i could not get `ILIKE` to work

2021-09-01 16:04 UTC, lukenewman commented on src/controllers/children/get.ts
> +    qb.andWhere('Child.fullName LIKE (:name)', {
`fullName` is lowercased in the `updateFullName` fn

2021-09-01 16:06 UTC, vonbearshark commented on src/migration/1630005495640-UpdateChildAddFullName.ts
> +}
> A computed column for name is added to the Child table, joining first and last name with a space. Should just be a simple DB migration

Ah yeah you're right. That is what I was suggesting, but ignore me!

2021-09-01 16:06 UTC, vonbearshark commented on client/src/containers/Overview/Overview.tsx
> +import { apiGet } from '../../utils/api';
Yeah I guess the diff is just confusing to me

2021-09-01 16:10 UTC, lukenewman commented on src/migration/1630005495640-UpdateChildAddFullName.ts
> +}
i will test that out. we definitely need to if the migration query doesn't trigger the `beforeUpdate()` fullname updater

2021-09-01 17:54 UTC, lukenewman commented on src/routes/children.ts
> +    const children = await controller.getChildren(req.user, name);
are you talking about something like this?

```
interface ChildrenQuery {
  searchTerm?: string;
  sorting?: string;
  ...
}
```

and then we map `req.query` onto that and then pass to the controller?

2021-09-01 18:02 UTC, vonbearshark commented on src/controllers/children/get.ts
> +    qb.andWhere('Child.fullName LIKE (:name)', {
> `fullName` is lowercased in the `updateFullName` fn

Oh yeah interesting just noticed. I re: my previous comments I don't fully get with this part of the AC myself, but even still my personal pitch would be if we are going to store it to maintain the casing. Unless we do this for other naming stuff already in the db?

2021-09-01 18:03 UTC, lukenewman commented on client/src/containers/Roster/Roster.tsx
> +        setChildRows(result.map(childToRow) ?? []);
can you expound on what the `try`/`catch` would include? handle server error as in show an error ui?

2021-09-01 18:04 UTC, vonbearshark commented on src/routes/children.ts
> +    const children = await controller.getChildren(req.user, name);
Yeah exactly like that. We shouldn't need to map anything--we should be able to pass it right in and then deconstruct it in the controller fn itself

2021-09-01 18:08 UTC, vonbearshark commented on client/src/containers/Roster/Roster.tsx
> +        setChildRows(result.map(childToRow) ?? []);
> as in show an error ui

That's what I am thinking. Here's an example from the `CreateOrg` stuff I am refactoring now https://github.com/ctoec/data-collection/blob/EPIC-roster-redesign/client/src/containers/CreateOrg/CreateOrg.tsx#L111. So, using our `alerts` system, with something like "Failed to load roster data", or something maybe

2021-09-01 18:26 UTC, vonbearshark commented on src/controllers/children/get.ts
> +    qb.andWhere('Child.fullName LIKE (:name)', {
Not sure if anything in this thread is useful https://github.com/typeorm/typeorm/issues/4418. There are some interesting workarounds there. Including maybe using `LOWER` on `Child.fullName`, like `LOWER(Child.fullName)`?

2021-09-01 20:01 UTC, lukenewman commented on client/src/containers/Roster/Roster.tsx
> +        setChildRows(result.map(childToRow) ?? []);
are you thinking something like this?

```
      (async function getRoster() {
        var path = 'children';
        if (searchTerm) {
          path += `?${stringify({searchTerm: searchTerm})}`;
        }
        const result = await apiGet(path, accessToken);
        setChildRows(result.map(childToRow));
      })().catch((error) => {
        setAlerts({ type: 'error', text: 'Failed to load roster' });
      });
```

2021-09-01 20:31 UTC, vonbearshark commented on src/controllers/children/get.ts
> +  var qb = await getManager()
nit: keep the `const`

2021-09-01 20:31 UTC, vonbearshark commented on client/src/containers/Roster/Roster.tsx
> +import { getErrorMessage } from '../CreateOrg/getErrorMessage';
nit: unused?

2021-09-01 20:31 UTC, vonbearshark commented on client/src/containers/Roster/Roster.tsx
> +      });
nit:

```
  useEffect(() => {
    if (accessToken) {
      (async function getRoster() {
        try {
          const result = await apiGet(
            `children?${stringify({ searchTerm })}`,
            accessToken
          );
          setChildRows(result.map(childToRow));
        } catch (error) {
          setAlerts((current) => [
            ...current,
            { type: 'error', text: 'Failed to load roster' },
          ]);
        }
      })();
    }
  }, [accessToken, searchTerm]);
```
?

updates `useEffect` deps, shorthands `searchTerm` object and stringification, try/catch for the api call itself, preserves current alerts in update

2021-09-01 22:34 UTC, lukenewman commented on src/migration/1630005495640-UpdateChildAddFullName.ts
> +}
i have confirmed that the latest migration successfully backfilled the `fullName` column in the `devsecure` env

2021-09-02 12:23 UTC, bamader reviewed
Functionally looking okay, just some things to change either stylistically or with regard to the DB.

2021-09-02 12:23 UTC, bamader commented on client/src/shared/models/db/Child.ts
> +  fullName?: string;
Do we need this field? My initial reaction is "no, because anytime we want to use the `fullName` we can just concatenate `firstName + middleName + lastName`". I know it's _possible_ to use concatenations like that with SQL (and I'd imagine this field exists to make the SQL querying easier), so have we tried doing that before generating a new DB column that will require migrating data? If this is strongly easier then no worries, just wanted to check if we can accomplish the job using what we have first.

2021-09-02 12:23 UTC, bamader commented on client/src/containers/Roster/Roster.tsx
> +          setChildRows(result.map(childToRow));
Nit: would prefer we stick to arrow function syntax here. I find it helps clarity and readability when looking at what this code is doing.

2021-09-02 12:23 UTC, bamader commented on client/src/containers/Roster/Roster.tsx
>      return {
Yeah going back to my earlier comment about merging in the `no-cache` code, it looks like there's some duplication; this `childToRow` function is in here twice. If we haven't merged those two together, we should to make sure we isolate duplicates and conflicts and clean them up now while we're still tweaking.

2021-09-02 12:23 UTC, bamader commented on src/controllers/children/get.ts
> +
Nit: do we need an interface to hold a single variable? Seems like it'd be more straightforward to me to just pass the search term directly into functions where it's needed.

2021-09-02 13:34 UTC, vonbearshark commented on client/src/shared/models/db/Child.ts
> +  fullName?: string;
lol see https://github.com/ctoec/data-collection/pull/1438#discussion_r700328426

2021-09-02 13:36 UTC, vonbearshark commented on client/src/containers/Roster/Roster.tsx
> +          setChildRows(result.map(childToRow));
For `result.map(childToRow)`?

2021-09-02 13:37 UTC, vonbearshark commented on src/controllers/children/get.ts
> +
This was my suggestion to make the Roster interface more generic for sort and pagination following this PR https://github.com/ctoec/data-collection/pull/1438#discussion_r700330737

2021-09-02 13:38 UTC, vonbearshark commented on src/entity/Child.ts
> +  fullName?: string;
Same re: https://github.com/ctoec/data-collection/pull/1438#discussion_r701088144. All 👀 on @JordanGuinn to say for sure. But your similar suspicious does reinforce my hunch imo..

2021-09-02 15:10 UTC, bamader commented on client/src/shared/models/db/Child.ts
> +  fullName?: string;
LOL okay, I'll take it 😂

2021-09-02 15:10 UTC, bamader commented on client/src/containers/Roster/Roster.tsx
> +    ageGroup,
Something to check for sure, especially given the duplicate function code

2021-09-02 15:11 UTC, bamader commented on client/src/containers/Roster/Roster.tsx
> +          setChildRows(result.map(childToRow));
Yeah. I just find an extra clarity boost in `result.map((c) => childToRow(c))`. Not a big deal if others don't mind it.

2021-09-02 15:11 UTC, bamader commented on src/controllers/children/get.ts
> +
That's fair. No real objection to it, and if you think it'll set up future work I'm all for it.

2021-09-02 15:12 UTC, bamader commented on src/entity/Child.ts
> +  fullName?: string;
HAHA I also missed that it was straight up part of the AC. Wow I need to up my review game...

2021-09-02 15:19 UTC, vonbearshark commented on client/src/containers/Roster/Roster.tsx
> +          setChildRows(result.map(childToRow));
It's my preference, but readability > preference, so fine to change. jw since I would do it in the future otherwise, so good to know

2021-09-02 15:24 UTC, lukenewman commented on client/src/containers/Roster/Roster.tsx
> +    ageGroup,
yeah this pr has the latest from that `no-cache` branch and also from a recent `base`. this dupe slipped past me!

2021-09-02 15:27 UTC, JordanGuinn commented on src/entity/Child.ts
> +  fullName?: string;
Check out [this Slack thread](https://skylight-hq.slack.com/archives/CM7D99AF3/p1629991490000900) for more details - TLDR; there was initial investigation into setting up as a virtual field, only to uncover that TypeORM doesn't actually support that (even though SQL Server itself does).  So it was decided that an actual field was the next best (or least worst) option

2021-09-02 15:30 UTC, JordanGuinn commented on client/src/shared/models/db/Child.ts
> +  fullName?: string;
Biggest concern around that strategy is performance - we'd have to generate that concatenation on each and every search attempt, and I'm not clear on what the implications of that would be

2021-09-02 15:35 UTC, JordanGuinn commented
In a nutshell, let's stick with `fullName` as an actual field because TypeORM doesn't really provide any actual support for virtual fields and on-the-fly field generation as a component of each search query doesn't seem like a particularly performant alternative

2021-09-02 15:35 UTC, lukenewman commented on client/src/containers/Roster/Roster.tsx
> +          setChildRows(result.map(childToRow));
it'll have to look like `result.map((c: any) => childToRow(c))

2021-09-02 15:36 UTC, bamader commented on client/src/shared/models/db/Child.ts
> +  fullName?: string;
Yeah totally fair

2021-09-02 15:36 UTC, bamader commented on src/entity/Child.ts
> +  fullName?: string;
This makes sense. No real objections to the actual field, especially if substantially improves our quality of life.

2021-09-02 15:44 UTC, JordanGuinn approved these changes
LGTM me overall - just one minor q regarding search init on keypress vs on click/enter

2021-09-02 15:44 UTC, JordanGuinn commented on client/src/containers/Roster/Roster.tsx
> +                    onChange={(input) => {
We want this to trigger on click, yes?  Just to avoid spamming the DB a bunch as the user types 😅

2021-09-02 15:44 UTC, JordanGuinn commented on src/controllers/children/get.ts
> +
Agreed - we'll be adding to this interface _very_ soon

2021-09-02 17:56 UTC, JordanGuinn commented on client/src/containers/Roster/Roster.tsx
> +                      if (event.key === 'Enter') {
hehehehe 😎

2021-09-03 16:42 UTC, nickbristow commented
## Validation Plan
- [ ] Search bar is on roster
- [ ] Search button can't be clicked if no text is entered
- [ ] hitting enter searches
- [ ] search is case insensitive
- [ ] search is fuzzy
- [ ] search matches against first and last name

2021-09-03 20:20 UTC, nickbristow commented
Search bar does not have a button, and requires you to hit enter key. Are we ok with this @JordanGuinn?

Also, only accepts first name last name and no commas, which may be confusing considering the table is listed as last name first name.

2021-09-03 20:32 UTC, nickbristow commented
@lukenewman Can we add a button and match the look of the mockups? Unless there was some decision made im not aware of?

2021-09-03 20:37 UTC, lukenewman commented
> @lukenewman Can we add a button and match the look of the mockups? Unless there was some decision made im not aware of?

@nickbristow we made the decision to roll with carbon's table components in the multi-select work since it has all the stuff we're looking for out-of-the-box. that being said, i'm not sure if there's a "search" button so will need to investigate

2021-09-03 23:51 UTC, JordanGuinn commented
Let's just use a native Carbon button, [as we're doing here](https://github.com/ctoec/component-library/blob/base/src/components/SearchBar/SearchBar.tsx).

2021-09-06 23:18 UTC, lukenewman commented
@nickbristow this is good to go again. users should be able to search on enter and search button click. clearing the search bar manually or via the X button should automatically refetch the roster

2021-09-07 14:33 UTC, nickbristow commented
Design doesn't exactly match, but functionality is good to go. 

<img width="1377" alt="Hogwarts_Childcare" src="https://user-images.githubusercontent.com/5296248/132363004-8cb26de7-5b02-4993-b259-e9726ccdeaa5.png">

2021-09-07 16:22 UTC, JordanGuinn commented
Confirmed that designs are good as-is for the time being - so if all else is well functionally, then this is ready for merge!

2021-09-07 16:43 UTC, merged