Funding types
ctoec/data-collection pull request #367
Opened 2020-09-24 21:14 UTC by bamader

Closes #328 
Closes #329

2020-09-24 21:15 UTC, jlhogan approved these changes

2020-09-24 21:15 UTC, jlhogan commented on client/src/shared/models/FundingSource.ts
> +  CDC = 'CDC - Child Day Care',
this totally works, and if we ever need to display just the short or long version, we can very easily split this string by `-`

2020-09-24 21:24 UTC, jlhogan requested changes
Just realized -- changing this enum requires a change to the DB since enum types are enforced via check constraint on string values. It's not the best set up but it's the easiest way to do the least custom stuff. if you have other ideas about how this could work (or want to do a little googling and see what other folks do) thats very welcome but not necessary by any means

2020-09-24 21:27 UTC, bamader commented
Oh good catch. I didn't even think of constraint checking. I'll do a bit of research to see what other people have used for it, but I'm not gonna spend too long on it. If there's an elegant solution, great, if not, we minimize custom code at the cost of a teeny bit of string checking.

2020-09-25 14:29 UTC, kmagida110 approved these changes
Approved, just a few questions for my own knowledge

2020-09-25 14:29 UTC, kmagida110 commented on client/src/components/Forms/EnrollmentFunding/Fields/Funding/NewFunding.tsx
> +            <RadioButton {...props} text="Unfunded" />
Naive Javascript question here but is there a reason this can't be the const UNFUNDED?

2020-09-25 14:29 UTC, kmagida110 commented on client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap
> +                PSR - Priority School Readiness
Where is the matching change for this?

2020-09-25 15:40 UTC, bamader commented on client/src/components/Forms/EnrollmentFunding/Fields/Funding/NewFunding.tsx
> +            <RadioButton {...props} text="Unfunded" />
Yep that's definitely the right move!

2020-09-25 15:41 UTC, bamader commented on client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap
> +                PSR - Priority School Readiness
When you say matching change, could you elaborate? This is a test snapshot that I had to update because I changed an element of the UI. It got automatically changed by the `docker-compose exec client yarn run test -u` command I mentioned in your PR.

2020-09-25 16:05 UTC, bamader commented
I did a little more research than I initially planned because it seemed like there would be some promising leads, but in the end I was pretty dissatisfied with all the solutions I find. I'm sticking with our string checks in the DB. I realized this ALSO means we need to modify the map function and a little bit of how enrollment data is processed when spreadsheets are uploaded. Since we don't want providers to have to fully type out 'CDC - Child Day Care' every time (they should be able to just do CDC), we want to make sure we modify the mapping function to not be like "oh you only typed CDC and not Child Day Care, I have no idea what this is".

2020-09-25 17:51 UTC, bamader commented
Update: DB changes have been made in constraint checks, and parsing for Source types has been updated so that providers don't have to enter in the full text in their spreadsheets.

2020-09-25 18:30 UTC, jlhogan approved these changes
one potential improvement to increase reusability (if we end up changing more enum values) but not a blocker

2020-09-25 18:30 UTC, jlhogan commented on src/controllers/enrollmentReports/map.ts
> +  firstLetterComparison: boolean = false,
would be cool if this was just a regex you pass in to match against instead of `firstLetterComparison` and `isFundingSource`

2020-09-25 18:35 UTC, bamader commented on src/controllers/enrollmentReports/map.ts
> +  firstLetterComparison: boolean = false,
I don't actually know why `firstLetterComparison` is there (maybe from some other check), but are you saying we should use a regex to decide what type of enum we're looking at?

2020-09-25 18:58 UTC, jlhogan commented on src/controllers/enrollmentReports/map.ts
> +  firstLetterComparison: boolean = false,
yeah no ignore me -- i thought it was doing a different thing and we could just use a regex to compare more programatically. but more complicated than i thought upon further inspection

2020-09-25 19:20 UTC, merged