541 add missing info column
ctoec/data-collection pull request #544
Opened 2020-10-09 14:57 UTC by kmagida110

Fixes #541

2020-10-09 15:28 UTC, bamader approved these changes
LGTM!

2020-10-09 16:32 UTC, mmazanec22 approved these changes

2020-10-09 16:32 UTC, mmazanec22 commented on client/src/containers/Roster/TableColumns.tsx
> +            {(!!row.validationErrors && row.validationErrors.length == 0) ||
!row.validationErrors || !row.validationErrors.length should cover all of this I think?

2020-10-09 16:34 UTC, jlhogan commented on client/src/containers/Roster/TableColumns.tsx
> +            {(!!row.validationErrors && row.validationErrors.length == 0) ||
agreed, i have this change in a diff branch but simpler conditionals is always a win IMO!!

2020-10-09 16:36 UTC, jlhogan requested changes

2020-10-09 16:36 UTC, jlhogan commented on client/src/containers/Roster/TableColumns.tsx
>            <th scope="row" className={tableRowClassName}>
this column should not be a th, should be td like the other rows

2020-10-09 16:38 UTC, kmagida110 commented on client/src/containers/Roster/TableColumns.tsx
> +            {(!!row.validationErrors && row.validationErrors.length == 0) ||
👍

2020-10-09 16:39 UTC, kmagida110 commented on client/src/containers/Roster/TableColumns.tsx
>            <th scope="row" className={tableRowClassName}>
Sounds good, copied this from the name, should name be td too?

2020-10-09 16:46 UTC, jlhogan commented on client/src/containers/Roster/TableColumns.tsx
>            <th scope="row" className={tableRowClassName}>
nope :) name is the header for the row (thus, `scope="row"`)

2020-10-09 20:28 UTC, kmagida110 commented on client/src/containers/Roster/TableColumns.tsx
>            <th scope="row" className={tableRowClassName}>
Fix is pushed, thanks @jlhogan

2020-10-11 18:40 UTC, jlhogan approved these changes

2020-10-12 13:56 UTC, merged