Implement single site user limitations
ctoec/data-collection pull request #615
Opened 2020-10-22 19:46 UTC by bamader

Implements access and UI restrictions for users with access to a single site that are part of an organization with multiple sites. As a note, I put the determination of whether the user was a single-site user of a multi-site provider in the backend, because it seems like something that user systems shouldn't have access to (i.e. if a user _does_ only have access to one site, we don't want the code that determines all the other sites their org provides for showing up in the front end). 

Closes #538

2020-10-22 20:37 UTC, jlhogan requested changes

2020-10-22 20:37 UTC, jlhogan commented on client/src/containers/Roster/Roster.tsx
> +  const [isSSUserOfMSProvider, setIsSSUser] = useState<boolean>(false);
so I think we can do this a bit more simply -- my thought was this: 
any user who is given permissions via "sitePermissions" is NOT an organization-level user and thus cannot do things like submit data, whether or not they have access to only one site, or to multiple sites. 

So it think we can remove this, and just look at the user object to see if they have any organization permissions, or if they only have site permissions.  Does that make sense?

2020-10-22 20:55 UTC, bamader commented on client/src/containers/Roster/Roster.tsx
> +  const [isSSUserOfMSProvider, setIsSSUser] = useState<boolean>(false);
I think it does, yeah. Lemme just see if I'm interpreting some fields correctly: a `User` object has `sites` and `organizations`, both of which are populated (on the backend, in the `authenticate.ts` file) via `sitePermissions` and `orgPermissions`. So the sites and orgs in those fields on a User are explicitly those the user can actually edit data for, rather than just sites/orgs the user is associated with? Based on how they're used on the roster page, I was thinking the `sites` and `organizations` arrays consisted of those the user was affiliated with (otherwise, a user could have elements in their `sites` array but nothing in their `organizations` array, and then that would make deciding how to format the header weird).

Follow-up (and this may be a question for Ryan): the ticket has a few characteristics in the AC for single-site users of multi-site providers: can't submit, can't see capacity, differently formatted page header, batch upload restrictions. Do we want to apply those four things to _all_ users who don't have orgPerms? Or just users who don't have orgPerms but also have access to only one site? If it's the latter case, I think we do need to know specifically whether the user is a single-site accessor of a multi-site organization. (This might be what you mean in your first paragraph with the other things part, but I just want to double check.)

Sorry for the long reply!

2020-10-23 14:56 UTC, bamader commented on client/src/containers/Roster/Roster.tsx
> +  const [isSSUserOfMSProvider, setIsSSUser] = useState<boolean>(false);
@RyanHansz Wanted to get your eyes on the second part of this question. Specifically, do we want the four restrictions in the AC of #538 to apply to all users who don't have org-level permissions?

2020-10-23 15:20 UTC, RyanHansz commented on client/src/containers/Roster/Roster.tsx
> +  const [isSSUserOfMSProvider, setIsSSUser] = useState<boolean>(false);
Yes, all the restrictions apply. 
"– If I batch upload, I can only replace/upload data for the site I have access to" would be (sites) for a multi-org user.

2020-10-23 15:24 UTC, jlhogan commented on client/src/containers/Roster/Roster.tsx
> +  const [isSSUserOfMSProvider, setIsSSUser] = useState<boolean>(false);
and my clarification/technical implementation addendum is:
-  an "all" site user is actually an "organization" user. we will grant permission/access to "all" sites by granting organization-level permissions to that user.
- a user who arbitrarily has access to "all" sites for an org via site permissions is not an edge case we care about.

2020-10-23 15:25 UTC, bamader commented on client/src/containers/Roster/Roster.tsx
> +  const [isSSUserOfMSProvider, setIsSSUser] = useState<boolean>(false);
Awesome. Thank you both! Can def simplify this then.

2020-10-23 15:29 UTC, bamader commented on client/src/containers/Roster/Roster.tsx
> +  const [isSSUserOfMSProvider, setIsSSUser] = useState<boolean>(false);
I like the idea of adding a convenience var to the model that captures access type. It's simple, provides the client the least information it needs to make this change, and keeps things on the backend where (to me at least) it makes the most sense to have that determination.

2020-10-23 15:31 UTC, bamader commented on client/src/containers/Roster/Roster.tsx
> +  const [isSSUserOfMSProvider, setIsSSUser] = useState<boolean>(false);
Yeah the terminology of the variable names was throwing me off a bit because I didn't realize they were convenience fields until I dug into authenticate and looked at how they got generated. I probs won't do anything with the cache because if we're gonna eventually swap that out with a package, I think it makes more sense to do the access type convenience field instead.

2020-10-26 15:01 UTC, jlhogan commented on client/src/containers/Roster/rosterUtils.tsx
> +  opts: { hideCapacity: boolean } = { hideCapacity: false }
can we put `showOrgInTables` into the `opts` object as well ?

2020-10-26 15:01 UTC, jlhogan commented on src/middleware/authenticate.ts
> +  user.accessType = allOrgIds.length === 0 ? 'site' : 'organization';
Can we make this determination based off the length of `orgPermissions` as opposed to `allOrgIds`? JIC some time in the future we want to populate site-level users with their parent org (could see that being convenient); wouldn't want access to get messed up from some change like that.

2020-10-26 15:19 UTC, bamader commented on client/src/containers/Roster/Roster.tsx
> +            : isSiteLevelUser
They definitely can. This conditional is there because in the design image of #538 , there's no "... at X sites" for the user. However, that issue was under the assumption we were only changing the UI for single site users rather than all site-level users. So question for @RyanHansz : can we still show the "...enrolled at X sites" text?

2020-10-26 15:19 UTC, bamader commented on client/src/containers/Roster/Roster.tsx
> +              ? 'Organization permissions required to submit'
That would make sense to me, and now that you say that I agree. Will wait for Ryan to confirm though.

2020-10-26 15:23 UTC, bamader commented on src/middleware/authenticate.ts
> +  user.accessType = allOrgIds.length === 0 ? 'site' : 'organization';
Yeah we def can. I just did `allOrgIds` in case there were relevant permissions stemming from the `orgsFromCommunities`.

2020-10-26 15:28 UTC, RyanHansz commented on client/src/containers/Roster/Roster.tsx
> +              ? 'Organization permissions required to submit'
Agree! Just hide the "submit to OEC" button in the bottom bar

2020-10-26 15:41 UTC, jlhogan commented on client/src/containers/Roster/Roster.tsx
> +            : isSiteLevelUser
my gut: If org user OR sites.length > 1, show. else, hide

2020-10-28 03:56 UTC, jlhogan approved these changes
some nits but overall LGTM !

2020-10-28 03:56 UTC, jlhogan commented on client/src/containers/Roster/Roster.tsx
> +import React, { useContext, useEffect, useState } from 'react';
cleanup unused imports

2020-10-28 03:56 UTC, jlhogan commented on client/src/containers/Roster/Roster.tsx
> +import { apiGet, apiPut } from '../../utils/api';
same, cleanup

2020-10-28 03:56 UTC, jlhogan commented on client/src/containers/Roster/Roster.tsx
> +    tabNavProps = undefined;
i'm not sure tabNav should disappear site-level user -- the org nav should, but user should still have sites nav (unless user has access to only one site)

2020-10-28 03:56 UTC, jlhogan commented on client/src/containers/Roster/Roster.tsx
> +            : user?.accessType === 'organization' || sites.length > 1
i think perhaps this ternary is backwards? If the user is organization access or the user has access to more than one site, then include the site in the string. Also, can avoid double nested ternary with something like, but that's just a preference :) 
```
{childrenCache.loading
  ? 'Loading...'
  : `${childrenCache.records.length} children enrolled at ${(user?.accessType === 'organization' || user?.sites.length > 1) ? `${sites.length} sites` : ''}`
```

2020-10-28 12:05 UTC, bamader commented on client/src/containers/Roster/Roster.tsx
> +    tabNavProps = undefined;
Good point, forgot to change this conditional from when I was trying to code the specific case of a single-site user. Will update.

2020-10-28 13:56 UTC, mmazanec22 commented on client/src/containers/Roster/Roster.tsx
> +  } else if (organizations.length === 1) {
The base case is a single site user (see line 108) so this should be unnecessary-- we can just change the default h1 to organization provderName

2020-10-28 13:56 UTC, mmazanec22 commented on client/src/containers/Roster/Roster.tsx
> +    if (sites.length == 1) tabNavProps = undefined;
If we leave the default as single site, then there's no need to set tab nav props to undefined here, since that's what they default to on line 115.  This can just be
```
if (sites.length > 1) {
  tabNavProps = {
    blablabla
  }
}
```

2020-10-28 16:53 UTC, mmazanec22 approved these changes

2020-10-28 18:03 UTC, merged