465 income det validation
ctoec/data-collection pull request #641
Opened 2020-10-27 00:06 UTC by mmazanec22

Closes #465

2020-10-27 16:20 UTC, jlhogan approved these changes

2020-10-27 16:20 UTC, jlhogan commented on client/src/components/Forms/FamilyIncome/AlertFosterIncomeNotRequired.tsx
> +export const AlertFosterIncomeNotRequired = () => (
nit: to me this name sounds like an action, i'd prefer `FosterIncomeNotRequiredAlert`

2020-10-27 16:20 UTC, jlhogan commented on client/src/components/Forms/FamilyIncome/Form.tsx
> +    // This shows up for new child
what does this mean?

2020-10-27 16:20 UTC, jlhogan commented on src/entity/Family.ts
> +  @MinLength(1)
wooooo was going to ask if we could throw this in here, but you already did !

2020-10-27 16:29 UTC, mmazanec22 commented on client/src/components/Forms/FamilyIncome/Form.tsx
> +    // This shows up for new child
I had to add this in two places bc of how we're conditionally showing forms in edit child-- can make this comment clearer

2020-10-27 16:51 UTC, jlhogan commented on src/entity/Family.ts
> +  @MinLength(1)
Just checked and this does not seem to validate the length of the nested array -- it's a string length validation. To validate array length, use `@ArrayMinSize(1)`

2020-10-27 16:59 UTC, jlhogan commented on src/entity/Family.ts
> +  @MinLength(1)
ok actually, i'm unable to get nested family validations working at all?

2020-10-27 17:31 UTC, jlhogan requested changes

2020-10-27 17:31 UTC, jlhogan commented on src/entity/Family.ts
> +  @ValidateIf((family) => family.children?.some((c: Child) => !c.foster))
as far as I can tell, this does _not_ actually work, because children is not populated on the family object

2020-10-27 17:53 UTC, jlhogan commented on src/entity/Family.ts
> +  @ValidateIf((family) => family.children?.some((c: Child) => !c.foster))
Kept playing around with this because was interested and what I cam up with is HACKY but also it WORKS :) 
in Child.ts:
```
@ValidateNested()
@ValidateIf((child) => { if(child.family) child.family.childIsFoster = child.foster; return true})
@ManyToOne(() => Family)
family?: Family;
```
in Family.ts:
```
@OneToMany(() => IncomeDetermination, (det) => det.family)
@ValidateNested({ each: true })
@ArrayMinSize(1)
@ValidateIf((family) => {const childIsFoster = family.childIsFoster; delete family.childIsFoster; return !childIsFoster})
incomeDeterminations?: Array<IncomeDetermination>;
```

2020-10-27 17:55 UTC, jlhogan commented on src/entity/Family.ts
> +  @ValidateIf((family) => family.children?.some((c: Child) => !c.foster))
improvement: write this as a custom decorator that's called something other than `ValidateIf`

2020-10-27 18:50 UTC, JordanGuinn commented on src/entity/Family.ts
> +  @ValidateIf((family) => family.children?.some((c: Child) => !c.foster))
Are there any situations where the `Family` object wouldn't be present on `Child`?  Also I'm legit AMAZED that attributes set in one validator persist when running another 😎

2020-10-27 18:54 UTC, jlhogan commented on src/entity/Family.ts
> +  @ValidateIf((family) => family.children?.some((c: Child) => !c.foster))
a lil perusal of the source code shows that the actual object instance is passed around everywhere, so just taking advantage of js pass by reference to update the old boy :) 

family is not present on the child when we do the `getChildren` call, which means family  + income determinations are not validated in the roster view. So ACTUALLY, if family is not present, we need to go pull it + income determinations from DB and validate those  OR just use the full query that we use for `getChildById` in the `getChildren` DB fetch (probably the latter -- easier and not really worth optimizing to save those like KB of data per record prob)

2020-10-27 18:58 UTC, jlhogan commented on src/entity/Family.ts
> +  @ValidateIf((family) => family.children?.some((c: Child) => !c.foster))
Actually i'm just gonna make that change in my branch b/c i need it to resolve a funky thing in batch edit :)

2020-10-27 20:34 UTC, mmazanec22 commented on src/entity/Family.ts
> +  @ValidateIf((family) => family.children?.some((c: Child) => !c.foster))
This appears to be working for me as is :thinking:

2020-10-28 01:50 UTC, JordanGuinn commented on src/entity/Child.ts
> +    if (child.family) child.family.childIsFoster = child.foster;
Would there be any potential situation where one child in a family is in foster care while the rest of the children are not?  Or vice versa?  

Wanna confirm that this doesn't introduce any possible edge cases or anything.

2020-10-28 03:49 UTC, jlhogan approved these changes
Add comments to explain the funky usage of validateIf but otherwise all good!

2020-10-28 03:49 UTC, jlhogan commented on src/entity/Child.ts
> +    if (child.family) child.family.childIsFoster = child.foster;
if we're gonna overload this validateIf, definitely want to comment !! 

re jordan's comment -- that's definitely a _potential_ situation, but right now there's a one to one child-family relationship (every child gets a new family even if in reality the children are siblings) so doesn't matter.
But even if we were reusing families correctly, and a family had foster and not foster children, this would work as expected.
But allllllso really i dont think thats an edge case we need to worry about.

2020-10-28 03:49 UTC, jlhogan commented on src/entity/Family.ts
> +  @ValidateIf((family) => {
comment!

2020-10-28 15:17 UTC, JordanGuinn approved these changes

2020-10-28 15:43 UTC, merged